//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPG_Remix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ficha
    {
        public Ficha()
        {
            this.Propriedades = new HashSet<Propriedade>();
            this.Peculiaridades = new HashSet<Peculiaridade>();
            this.Riquezas = new HashSet<Riqueza>();
            this.ItensArmas = new HashSet<ItemArma>();
            this.Vestimenta = new HashSet<Vestimenta>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public int Idade { get; set; }
        public string Raca { get; set; }
        public string Classe { get; set; }
        public int Adre { get; set; }
        public int Ataq { get; set; }
        public int Defe { get; set; }
        public int Dest { get; set; }
        public int Forc { get; set; }
        public int Inte { get; set; }
        public int Resi { get; set; }
        public int Sabe { get; set; }
        public int Velo { get; set; }
        public int Vital { get; set; }
        public int Sort { get; set; }
        public int Suportes { get; set; }
        public int UsuarioId { get; set; }
        public int MesaId { get; set; }
        public int PtsTestes { get; set; }
        public int PtsPericias { get; set; }
        public int PtsDesvantagens { get; set; }
        public int PtsExperiencia { get; set; }
        public string DataNivel { get; set; }
    
        public virtual ICollection<Propriedade> Propriedades { get; set; }
        public virtual ICollection<Peculiaridade> Peculiaridades { get; set; }
        public virtual ICollection<Riqueza> Riquezas { get; set; }
        public virtual ICollection<ItemArma> ItensArmas { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Mesa Mesa { get; set; }
        public virtual ICollection<Vestimenta> Vestimenta { get; set; }
    }
}
