//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPG_Remix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mapa
    {
        public Mapa()
        {
            this.Regiões = new HashSet<Região>();
            this.MesaMapa = new HashSet<MesaMapa>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public string Caminho { get; set; }
        public bool Geral { get; set; }
    
        public virtual ICollection<Região> Regiões { get; set; }
        public virtual ICollection<MesaMapa> MesaMapa { get; set; }
    }
}
