//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPG_Remix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesa
    {
        public Mesa()
        {
            this.Ficha = new HashSet<Ficha>();
            this.MesaMapa = new HashSet<MesaMapa>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public Nullable<int> NumeroJogadores { get; set; }
        public string DataCriacao { get; set; }
        public string Senha { get; set; }
        public int UsuarioId { get; set; }
    
        public virtual ICollection<Ficha> Ficha { get; set; }
        public virtual ICollection<MesaMapa> MesaMapa { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
