//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPG_Remix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mestre
    {
        public Mestre()
        {
            this.Fichas = new HashSet<Ficha>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public int UsuarioId { get; set; }
    
        public virtual Mesa Mesa { get; set; }
        public virtual ICollection<Ficha> Fichas { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
