//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPG_Remix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Região
    {
        public Região()
        {
            this.Propriedades = new HashSet<Propriedade>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public int MapaId { get; set; }
    
        public virtual ICollection<Propriedade> Propriedades { get; set; }
        public virtual Mapa Mapa { get; set; }
    }
}
