//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPG_Remix.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RemixRPGContainer : DbContext
    {
        public RemixRPGContainer()
            : base("name=RemixRPGContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Mesa> MesaSet { get; set; }
        public DbSet<Usuario> UsuarioSet { get; set; }
        public DbSet<Ficha> FichaSet { get; set; }
        public DbSet<Experiencia> ExperienciaSet { get; set; }
        public DbSet<Peculiaridade> PeculiaridadeSet { get; set; }
        public DbSet<Propriedade> PropriedadeSet { get; set; }
        public DbSet<Riqueza> RiquezaSet { get; set; }
        public DbSet<ItemArma> ItemArmaSet { get; set; }
        public DbSet<Vestimenta> VestimentaSet { get; set; }
        public DbSet<PontosAcumulados> PontosAcumuladosSet { get; set; }
        public DbSet<Jogador> JogadorSet { get; set; }
        public DbSet<Mestre> MestreSet { get; set; }
        public DbSet<Mapa> MapaSet { get; set; }
        public DbSet<Região> RegiãoSet { get; set; }
    }
}
