//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPG_Remix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Ficha = new HashSet<Ficha>();
            this.Mesa = new HashSet<Mesa>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public string Email { get; set; }
        public string Senha { get; set; }
        public string DataNascimento { get; set; }
        public byte Sexo { get; set; }
        public string DataCadastro { get; set; }
    
        public virtual ICollection<Ficha> Ficha { get; set; }
        public virtual ICollection<Mesa> Mesa { get; set; }
    }
}
