//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPG_Remix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jogador
    {
        public int Id { get; set; }
    
        public virtual Mesa Mesa { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Ficha Ficha { get; set; }
    }
}
