//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPG_Remix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vestimenta
    {
        public int Id { get; set; }
        public string Testa { get; set; }
        public string Cara { get; set; }
        public string Pescoco { get; set; }
        public string OmbroD { get; set; }
        public string OmbroE { get; set; }
        public string BracoD { get; set; }
        public string BracoE { get; set; }
        public string AntebracoD { get; set; }
        public string AntebracoE { get; set; }
        public string MaoD { get; set; }
        public string MaoE { get; set; }
        public string PeitoD { get; set; }
        public string PeitoE { get; set; }
        public string Diafragma { get; set; }
        public string Abdomen { get; set; }
        public string Genital { get; set; }
        public string CoxaD { get; set; }
        public string CoxaE { get; set; }
        public string JoelhoD { get; set; }
        public string JoelhoE { get; set; }
        public string CanelaD { get; set; }
        public string CanelaE { get; set; }
        public string PeD { get; set; }
        public string PeE { get; set; }
    
        public virtual Ficha Ficha { get; set; }
        public virtual ItemArma ItemArma { get; set; }
    }
}
